version: '3.8'
services:
  gateway:
    build: gateway
    image: shareit-gateway:latest
    container_name: shareit-gateway
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - server
    environment:
      - SHAREIT_SERVER_URL=http://server:9090

  server:
    build: server
    image: shareit-server:latest
    container_name: shareit-server
    ports:
      - "9090:9090"
      - "9091:9091"
    depends_on:
      - db
    environment:
      - URL_DB=postgresql://db:5432/shareit
      - USERNAME_DB=postgres
      - PASSWORD_DB=123

  db:
    image: postgres_db
    build:
      context: ./
      dockerfile: ./Dockerfile.postgres

    volumes:
      - /var/lib/postgresql/data/
    container_name: shareit-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=shareit
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123