CREATE TABLE IF NOT EXISTS item_request (
    item_request_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description VARCHAR(255)                   NOT NULL,
    user_id BIGINT                             NOT NULL,
    created TIMESTAMP WITHOUT TIME ZONE        NOT NUll,
    CONSTRAINT pk_item_request PRIMARY KEY (item_request_id)
);

CREATE TABLE IF NOT EXISTS users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255)                          NOT NULL,
    email VARCHAR(512)                         NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (user_id),
    CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS items (
    item_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(20)                           NOT NULL,
    description VARCHAR(50)                    NOT NULL,
    available BOOLEAN                          NOT NULL,
    owner BIGINT                               NOT NULL,
    request BIGINT,
    CONSTRAINT pk_items PRIMARY KEY (item_id),
    CONSTRAINT fk_items_users FOREIGN KEY (owner) REFERENCES users(user_id),
    CONSTRAINT fk_item_item_request FOREIGN KEY (request) REFERENCES item_request(item_request_id)
);

